### ISSUE TITLE
[feature-proxy branch] Old AltUnity name and version still appearing in AltTesterPrefab

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1001]
### AR
 
On the `feature-proxy` branch, in `AltTesterPrefab` the old `AltUnity` name is still present in the `AltUnityDialog` element and also in the `Title` for `Dialog` on the connection phase of starting the communication protocol, along with an old version of the Tester.

### Additional info
 
Screenshot 
![image](https://user-images.githubusercontent.com/62327834/203927226-c9d00aa7-8350-4e69-8150-43d4baef6d9b.png)

### ER
 
Only the AltTester name and current version should be present in the elements of `AltTesterPrefab`

**Comment by iulianatodoran** [comment]
@sandraaltom I put this in Backlog

**Comment by robert-altom** [comment]
@iulianatodoran I can't reproduce the issue. I also look in the code an there is no mention of `AltUnity Tester`. 

Maybe you saved an older version of the `AltTesterPrefab` in your scene, you can try to remove it from the scene and run the project again, this should fix the issue.

**Comment by iulianatodoran** [comment]
The issue is still reproducing, checked with @robert-altom.
Will move the ticket from **Testing** back in **Doing**

**Comment by iulianatodoran** [comment]
### Testing Environment
- OS: Windows 10/ macOS Big Sur v 11.6.8
- Unity v 2021.3.15f1 (Windows) and v 2021.3.5f1 (Mac)
- AltTester Unity SDK v 1.8.1 (alpha)- latest from `development` branch in 14.12.22
- AltTester Unity SDK v 1.8.0 - from `feature-proxy` branch

### Tests performed and results
- :heavy_check_mark: Checked in Unity that only the `AltTester` name and current version are present in the elements of `AltTesterPrefab` for both the `development` and `feature-proxy` branches in all possible scenarios for the prefab (starting communication, waiting for connections, connected)

### Conclusions
The purpose of this ticket was achieved.
Closing the ticket.
